// Actual source APIs against disposable state; no provider install or execution.
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const worker=spawn(process.env.USTAM_TEST_PYTHON||'python3',['-u','tests/ustam_install_fixture.py'],{cwd:path.resolve(__dirname,'..')});let browser;
try{const fixture=await new Promise((resolve,reject)=>{let output='';worker.stdout.on('data',chunk=>{output+=chunk;if(output.includes('\n'))resolve(JSON.parse(output.split('\n')[0]));});worker.stderr.on('data',c=>process.stderr.write(c));worker.on('exit',code=>reject(Error('Fixture exit '+code)));});
browser=await chromium.launch({headless:true,channel:process.env.USTAM_TEST_BROWSER||'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const posts=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')posts.push(new URL(r.url()).pathname);});await page.addInitScript(()=>{localStorage.setItem('ustam-language','en');localStorage.setItem('ustam-onboarded','1');});
const get=async()=>await (await page.request.get(fixture.origin+'/api/bootstrap')).json();let snapshot=await get();const id=fixture.ids[0];const codexOverride={orchestras:{codex:'codex-team'},note:'preserve existing project preference'};const set=await page.request.post(fixture.origin+'/api/defaults',{headers:{'X-Ustam-CSRF':snapshot.csrf,Origin:fixture.origin},data:{revision:snapshot.revision,selected_providers:['codex'],project_id:id,override:codexOverride}});assert.equal(set.status(),200);snapshot=await get();const baseline=JSON.parse(JSON.stringify(snapshot));
await page.goto(fixture.origin);await page.locator('.select-project').first().waitFor();await page.evaluate(()=>{window.pickerNodes=[document.querySelector('.hero img'),document.querySelector('#view > .cards'),...document.querySelectorAll('#view > .cards article')];});await page.locator('#view > .cards article').first().getByRole('button',{name:'Change team',exact:true}).click();const picker=()=>page.locator('#project-orchestra-choice').getByLabel('Tool',{exact:true});assert.deepEqual(await picker().locator('option').evaluateAll(els=>els.map(e=>e.value)),['codex','claude','opencode','antigravity']);
for(const provider of ['claude','opencode','antigravity','codex','antigravity']){await picker().selectOption(provider);await page.locator('#project-orchestra-choice [data-profile]').first().waitFor();assert.equal(await picker().inputValue(),provider);assert.ok(await page.evaluate(()=>window.pickerNodes.every(n=>n.isConnected)));}assert.deepEqual(posts,[]);assert.deepEqual((await get()).project_overrides,baseline.project_overrides);
const evidence=process.env.USTAM_UI_EVIDENCE||'/tmp/ustam-provider-picker';fs.mkdirSync(evidence,{recursive:true});await picker().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(evidence,'picker-desktop.png')});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);await picker().scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(evidence,'picker-mobile.png')});
await page.locator('[data-profile="balanced"]').getByRole('button',{name:'Review team',exact:true}).click();await page.locator('#inline-team-preview').getByRole('button',{name:'Use for this project',exact:true}).click();await page.locator('.project-flow[data-provider="antigravity"]').getByRole('button',{name:'Install in project',exact:true}).waitFor();snapshot=await get();assert.deepEqual(snapshot.selected_providers,['codex']);const override=snapshot.project_overrides[id];assert.equal(override.note,codexOverride.note);assert.equal(override.orchestras.codex,'codex-team');const team=snapshot.orchestras.find(o=>o.id===override.orchestras.antigravity);assert.ok(team);assert.equal(team.provider,'antigravity');assert.equal(team.helpers.length,4);assert.ok([team.chief,...team.helpers].every(a=>a.effort===''));assert.equal(posts.filter(p=>p==='/api/preview'||p==='/api/apply'||p==='/api/restore'||p==='/api/jobs').length,0);assert.equal(fs.existsSync(path.join(fixture.root,'Alpha','.agents')),false);
// Exercise explicit install validation on disposable state, with a failed preview preventing writes.
let previewBody;await page.route('**/api/models?*',async route=>{const response=await route.fetch();const body=await response.json();if(body.result.provider==='antigravity')body.result.support_matrix={...body.result.support_matrix,cli:{status:'supported',version:'1.2.16',reason:'synthetic support for provider routing check'},native_agents:{status:'local_help_verified'}};await route.fulfill({response,json:body});});await page.route('**/api/preview',async route=>{previewBody=route.request().postDataJSON();await route.fulfill({json:{ok:true,results:[{project_id:id,ok:false,error:'Fixture stops before any write'}]}});});await page.locator('.project-flow[data-provider="antigravity"]').getByRole('button',{name:'Install in project',exact:true}).click();await page.locator('#modal .result.error').waitFor();assert.equal(previewBody.provider,'antigravity');assert.equal(previewBody.payload.provider,'antigravity');assert.equal(posts.filter(p=>p==='/api/apply').length,0);await page.locator('#modal .modal-actions').getByRole('button',{name:'Close',exact:true}).click();
// Explicit per-project provider survives the same dropdown helper in restore, without submitting it.
await page.locator('.project-flow[data-provider="antigravity"]').getByRole('button',{name:'Undo last change',exact:true}).click();assert.equal(await page.locator('#modal').getByLabel('Tool',{exact:true}).inputValue(),'antigravity');await page.locator('#modal .modal-actions').getByRole('button',{name:'Cancel',exact:true}).click();assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,cases:['Codex-only global preference exposes all four supported tools in project chooser','provider changes cause no POST and retain project/hero DOM','actual Hub save accepts Antigravity ready team','Codex override and global preference preserved','no silent install; explicit preview routes Antigravity and fails without apply or project writes','explicit restore provider retained','desktop/mobile no overflow'],sourceAPIs:true}));
}finally{if(browser)await browser.close();worker.kill('SIGINT');}})().catch(e=>{console.error(e);process.exitCode=1;});
