// Disposable UI fixture and routed usage only: no live state or provider calls.
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{
 const worker=spawn(process.env.USTAM_TEST_PYTHON||'python3',['-u','tests/ustam_install_fixture.py'],{cwd:path.resolve(__dirname,'..')});let browser;
 try{
 const fixture=await new Promise((resolve,reject)=>{let output='';worker.stdout.on('data',chunk=>{output+=chunk;if(output.includes('\n'))resolve(JSON.parse(output.split('\n')[0]));});worker.stderr.on('data',chunk=>process.stderr.write(chunk));worker.on('exit',code=>reject(Error('Fixture exited '+code)));});
 browser=await chromium.launch({headless:true,channel:process.env.USTAM_TEST_BROWSER||'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];let requests=0,aborted=0,mode='delayed',release;
 page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',request=>{if(new URL(request.url()).pathname==='/api/usage')aborted++;});
 await page.addInitScript(()=>{localStorage.setItem('ustam-language','tr');localStorage.setItem('ustam-onboarded','1');});
 const result={source:'Disposable fixture',totals:{total_tokens:24,input_tokens:20,output_tokens:4,cached_input_tokens:0},runs:[],installation_boundary:{status:'verified',started_at:'2000-01-01T00:00:00Z'},records:[{actor_id:'locale-chief',timestamp:new Date().toISOString(),usage:{total_tokens:24,input_tokens:20,output_tokens:4,cached_input_tokens:0}}],actors:[{id:'locale-chief',role:'chief',total_tokens:24,input_tokens:20,output_tokens:4}]};
 await page.route('**/api/usage?*',async route=>{requests++;if(mode.startsWith('delayed'))await new Promise(resolve=>release=resolve);if(mode.endsWith('error'))return route.fulfill({status:500,json:{ok:false,error:{message:'fixture diagnostic retained'}}});await route.fulfill({json:{ok:true,result}});});
 await page.goto(fixture.origin);await page.locator('.select-project').first().waitFor();const language=page.locator('#language');const notice=page.locator('#notice');
 await language.selectOption('en');assert.ok(await notice.isHidden());await language.selectOption('tr');
 await page.locator('#nav').getByRole('button',{name:'Kullanım',exact:true}).click();await page.getByRole('button',{name:'Kullanımı getir',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('1 sn geçti'));assert.equal(requests,1);await language.selectOption('en');assert.equal(requests,1);assert.equal(aborted,0);assert.ok(await page.locator('.usage-toolbar .primary').isDisabled());release();await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Done');assert.equal(requests,1);assert.deepEqual(await page.locator('.metric strong').allTextContents(),['24','20','4','0']);assert.equal(await page.locator('.metric[data-usage-observed="true"]').count(),4);const firstLoad={requests,aborted,expected:['24','20','4','0'],displayed:await page.locator('.metric strong').allTextContents(),notice:await notice.innerText()};await page.screenshot({path:'/tmp/current-ui-locale-first-load.png',animations:'disabled'});await language.selectOption('tr');
 await notice.evaluate(el=>{window.localeNotice=el;window.localeMessage=el.firstElementChild;});await language.selectOption('en');assert.equal(await notice.innerText(),'Done');assert.ok(await notice.evaluate(el=>el===window.localeNotice&&el.firstElementChild===window.localeMessage));assert.ok(await notice.evaluate(el=>el.classList.contains('success')));assert.equal(await page.locator('.metric strong').first().innerText(),'24');
 await language.selectOption('tr');assert.equal(await notice.innerText(),'Tamamlandı');
 mode='error';await page.getByRole('button',{name:'Kullanımı getir',exact:true}).click();await notice.locator('details').waitFor();await notice.locator('summary').click();await notice.locator('details').evaluate(el=>window.localeDetail=el);
 await language.selectOption('en');assert.match(await notice.innerText(),/^The action could not be completed/);assert.equal(await notice.locator('summary').innerText(),'Show details');assert.match(await notice.innerText(),/fixture diagnostic retained/);assert.ok(await notice.locator('details').evaluate(el=>el===window.localeDetail&&el.open));assert.ok(await notice.evaluate(el=>el.classList.contains('error')));
 await language.selectOption('tr');mode='delayed';await page.getByRole('button',{name:'Kullanımı getir',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('1 sn geçti'));const elapsed=(await notice.innerText()).match(/(\d+) sn geçti/)[1];const before=requests;
 await notice.evaluate(el=>{window.pendingNotice=el;window.pendingMessage=el.firstElementChild;});await language.selectOption('en');assert.match(await notice.innerText(),new RegExp(elapsed+'s elapsed'));assert.match(await notice.innerText(),/The first scan may take longer/);assert.ok(await notice.evaluate(el=>el===window.pendingNotice&&el.firstElementChild===window.pendingMessage&&el.classList.contains('busy')));assert.equal(requests,before);assert.equal(aborted,0);release();await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Done');assert.equal(aborted,0);assert.deepEqual(await page.locator('.metric strong').allTextContents(),['24','20','4','0']);
 mode='delayed-error';await page.getByRole('button',{name:'Load usage',exact:true}).click();await page.waitForTimeout(60);await language.selectOption('tr');release();await notice.locator('details').waitFor();assert.ok(await notice.evaluate(el=>el.classList.contains('error')));assert.match(await notice.innerText(),/İşlem tamamlanamadı/);assert.deepEqual(await page.locator('.metric strong').allTextContents(),['24','20','4','0']);
 mode='success';await page.getByRole('button',{name:'Kullanımı getir',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Tamamlandı');
 mode='delayed';await page.getByRole('button',{name:'Kullanımı getir',exact:true}).click();await page.waitForTimeout(60);await language.selectOption('en');await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('collection cancelled'));assert.deepEqual(await page.locator('.metric strong').allTextContents(),['24','20','4','0']);assert.ok(await page.getByRole('button',{name:'Load usage',exact:true}).isEnabled());release();await page.waitForTimeout(60);
 await page.evaluate(()=>{window.localeNativeTimeout=window.setTimeout;window.setTimeout=(fn,ms,...args)=>window.localeNativeTimeout(fn,ms===180000?300:ms,...args);});await page.getByRole('button',{name:'Load usage',exact:true}).click();await language.selectOption('tr');await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('zaman aşımına'));assert.ok(await notice.evaluate(el=>el.classList.contains('error')));assert.deepEqual(await page.locator('.metric strong').allTextContents(),['24','20','4','0']);release();await page.evaluate(()=>window.setTimeout=window.localeNativeTimeout);await page.waitForTimeout(60);
 await page.getByRole('button',{name:'Kullanımı getir',exact:true}).click();await page.waitForTimeout(60);await language.selectOption('en');await page.getByLabel('Project',{exact:true}).selectOption(fixture.ids[1]);await page.waitForFunction(()=>!document.querySelector('.usage-toolbar .primary').disabled);release();await page.waitForTimeout(80);assert.deepEqual(await page.locator('.metric strong').allTextContents(),['0','0','0','0']);assert.equal(await page.locator('.metric[data-usage-observed="false"]').count(),4);
 await page.getByLabel('Project',{exact:true}).selectOption(fixture.ids[0]);mode='success';await page.getByRole('button',{name:'Load usage',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Done');assert.deepEqual(await page.locator('.metric strong').allTextContents(),['24','20','4','0']);
 await page.setViewportSize({width:390,height:844});await language.selectOption('tr');assert.equal(await notice.innerText(),'Tamamlandı');await language.selectOption('en');assert.equal(await notice.innerText(),'Done');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/current-ui-locale-fix-mobile.png',animations:'disabled'});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,firstLoad,requests,aborted,cases:['first load without cache survives TR→EN with one GET/nonzero 24','hidden stays hidden','usage success TR→EN→TR','cached usage retained','notice/message DOM retained','error detail/open state retained','numeric progress args retained','inflight fetch not restarted or aborted','pending failure after locale handoff stays error/cache retained','locale pending cancel keeps cache','locale pending timeout keeps cache','locale then project change rejects late response','mobile translated/no overflow']}));
 }finally{if(browser)await browser.close();worker.kill('SIGINT');}
})().catch(error=>{console.error(error);process.exitCode=1;});
