// Disposable server and routed records: no real project writes or provider calls.
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');const path=require('node:path');const assert=require('node:assert/strict');
const hash=name=>({contract:'a',policy:'b',pack:'c',candidate:'d',old:'e',combined:'f',main:'1',tree:'2',runner:'3'}[name]).repeat(64);
(async()=>{
 const worker=spawn(process.env.USTAM_TEST_PYTHON||'python3',['-u','tests/ustam_install_fixture.py'],{cwd:path.resolve(__dirname,'..')});let browser;
 try{
 const fixture=await new Promise((resolve,reject)=>{let output='';worker.stdout.on('data',chunk=>{output+=chunk;if(output.includes('\n'))resolve(JSON.parse(output.split('\n')[0]));});worker.stderr.on('data',chunk=>process.stderr.write(chunk));worker.on('exit',code=>reject(Error('Fixture exited '+code)));});
 browser=await chromium.launch({headless:true,channel:process.env.USTAM_TEST_BROWSER||'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],posts=[];let works=[];let fail=false;let delayed=false;
 page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{localStorage.setItem('ustam-language','tr');localStorage.setItem('ustam-onboarded','1');});
 await page.route('**/api/works',async route=>{const request=route.request();if(request.method()==='GET')return route.fulfill({json:{schema_version:1,works}});const body=request.postDataJSON();posts.push(body);if(delayed)await new Promise(r=>setTimeout(r,250));if(fail){fail=false;works[0].version++;return route.fulfill({status:409,json:{ok:false,error:{message:'Work version changed; refresh before answering or changing it'}}});}const work=works.find(w=>w.id===body.id);if(body.action==='approve'){work.approved_hash=work.contract_hash;work.approval_required=false;work.approval_basis='trusted_ustam_control';};if(body.action==='answer')for(const w of works)for(const q of w.questions||[])if(q.key==='decision')q.answer=body.answer;if(body.action==='apply')work.status='applied';if(body.action==='cancel')work.status='cancelled';if(body.action==='resume')work.status='contract';return route.fulfill({json:{work}});});
 await page.goto(fixture.origin);await page.locator('.select-project').first().waitFor();await page.getByRole('button',{name:'Çalışmalar',exact:true}).click();await page.locator('.works-empty').waitFor();assert.equal(posts.length,0);assert.equal(await page.locator('#view textarea').count(),0);assert.match(await page.locator('.works-empty').innerText(),/Kurulum çalışma oluşturmaz/);
 const base={project_id:'p1',provider:'codex',version:1,contract:{scope:'Mobil menüyü düzelt',criteria:['Menü küçük ekranda açılır'],files:['menu.js'],commands:[]},contract_hash:hash('contract'),approved_hash:null,approval_required:true,policy_hash:hash('policy'),status:'contract',receipts:[],test_pack:null,candidate:null,workspace:null,questions:[],events:[]};
 const question={id:'q1',key:'decision',question:'Menü rengi ne olsun?',options:['Bordo','Krem'],versions:{one:1,two:1},answer:null};works=[{...base,id:'one',questions:[question]},{...base,id:'two',questions:[{...question,id:'q2'}],approved_hash:hash('contract'),approval_required:false,approval_basis:'standing_policy',receipts:[{provenance:'helper_reported',status:'unverified'}]}];
 await page.getByRole('button',{name:'Yenile',exact:true}).click();await page.locator('[data-work-id="one"]').waitFor();assert.equal(await page.locator('.work-question').count(),1);assert.match(await page.locator('[data-work-id="two"]').innerText(),/çalıştırılmış kontrol kanıtı değildir/);
 await page.locator('[data-work-id="one"]').evaluate(el=>window.workCard=el);await page.getByRole('button',{name:'Yenile',exact:true}).click();await page.waitForTimeout(100);assert.ok(await page.locator('[data-work-id="one"]').evaluate(el=>el===window.workCard));
 delayed=true;const approve=page.getByRole('button',{name:'Bu kapsamı onayla',exact:true});await approve.click();assert.ok(await approve.isDisabled());await page.waitForFunction(()=>!document.querySelector('[data-work-id="one"] button')?.disabled);delayed=false;assert.equal(posts.filter(p=>p.action==='approve').length,1);assert.equal(posts[0].contract_hash,hash('contract'));assert.equal(posts[0].version,1);assert.ok(posts[0].operation_id);
 await page.getByRole('button',{name:'Bordo',exact:true}).click();await page.getByRole('button',{name:'Yenile',exact:true}).click();await page.waitForTimeout(100);assert.equal(await page.getByRole('textbox',{name:'Bu karara yanıtınız'}).inputValue(),'Bordo');await page.getByRole('button',{name:'Yanıtı paylaş',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.work-question'));assert.equal(posts.at(-1).answer,'Bordo');
 const restored=JSON.parse(JSON.stringify(works));
 const sparse={...base,id:'malformed',status:'ready_to_apply',approval_basis:'trusted_ustam_control',approval_required:false,candidate:{},contract_hash:undefined,approved_hash:undefined,policy_hash:undefined,test_pack_hash:undefined,receipts:[{provenance:'controller_observed',runner:'local_work_protocol',role:'verifier',status:'passed'}],integration:{provenance:'controller_observed',runner:'local_work_protocol',status:'passed'},integration_hash:hash('combined')};
 for(const value of [undefined,null,'']){const malformed={...sparse,contract_hash:value,approved_hash:value,policy_hash:value,test_pack_hash:value,candidate:{hash:value,contract_hash:value,pack_hash:value}};works=[malformed];await page.getByRole('button',{name:'Yenile',exact:true}).click();await page.waitForTimeout(80);const card=page.locator('[data-work-id="malformed"]');assert.equal(await page.getByRole('button',{name:'Bu değişiklikleri projeye uygula'}).count(),0);assert.doesNotMatch(await card.innerText(),/Kapsamı siz onayladınız|kontrol çalıştırıldı: geçti|proje kontrolü: geçti/);}
 works=restored;
 works[0]={...works[0],status:'ready_to_apply',test_pack:{checks:[]},test_pack_hash:hash('pack'),candidate:{hash:hash('candidate'),contract_hash:hash('contract'),pack_hash:hash('pack')},workspace:'/temporary/work',receipts:[{provenance:'controller_observed',runner_hash:hash('runner'),runner:'local_work_protocol',role:'verifier',policy_hash:hash('policy'),candidate_hash:hash('old'),contract_hash:hash('contract'),test_pack_hash:hash('pack'),status:'passed'}],integration:{status:'passed',main_hash:hash('main'),combined_tree_hash:hash('tree'),runner_hash:hash('runner'),runner:'local_work_protocol',provenance:'controller_observed',contract_hash:hash('contract'),policy_hash:hash('policy'),candidate_hash:hash('candidate'),pack_hash:hash('pack')},integration_hash:hash('combined')};
 const {evidenceState,humanApproved}=await import('../ustam/ui/works-view.mjs');
 const valid=JSON.parse(JSON.stringify(works[0]));valid.receipts[0].candidate_hash=hash('candidate');assert.equal(evidenceState(valid).ready,true);assert.equal(humanApproved(valid),true);
 const bindingPaths=[['candidate','hash'],['candidate','contract_hash'],['candidate','pack_hash'],['contract_hash'],['policy_hash'],['test_pack_hash'],['receipts',0,'candidate_hash'],['receipts',0,'contract_hash'],['receipts',0,'policy_hash'],['receipts',0,'test_pack_hash'],['receipts',0,'runner_hash']];
 const integrationPaths=[['integration','candidate_hash'],['integration','contract_hash'],['integration','policy_hash'],['integration','pack_hash'],['integration','main_hash'],['integration','combined_tree_hash'],['integration','runner_hash'],['integration_hash']];
 for(const keys of [...bindingPaths,...integrationPaths])for(const value of [undefined,null,'','not-a-hash']){const bad=JSON.parse(JSON.stringify(valid));let target=bad;for(const key of keys.slice(0,-1))target=target[key];target[keys.at(-1)]=value;const proof=evidenceState(bad);assert.equal(proof.ready,false,keys.join('.'));if(bindingPaths.includes(keys)){assert.equal(proof.passed,false);assert.equal(proof.combined,false);}else if(keys[0]==='integration')assert.equal(proof.combined,false);}
 for(const value of [undefined,null,0,'false',true]){assert.equal(evidenceState({...valid,approval_required:value}).ready,false);assert.equal(humanApproved({...valid,approval_required:value}),false);}
 for(const value of [undefined,null,'','not-a-hash'])assert.equal(humanApproved({...valid,contract_hash:value,approved_hash:value}),false);
 assert.equal(humanApproved({...valid,approval_basis:'standing_policy'}),false);
 await page.getByRole('button',{name:'Yenile',exact:true}).click();await page.waitForTimeout(100);assert.equal(await page.getByRole('button',{name:'Bu değişiklikleri projeye uygula'}).count(),0);assert.match(await page.locator('[data-work-id="one"]').innerText(),/Önceki kontrol/);
 works[0].receipts[0].candidate_hash=hash('candidate');await page.getByRole('button',{name:'Yenile',exact:true}).click();await page.getByRole('button',{name:'Bu değişiklikleri projeye uygula'}).waitFor();await page.screenshot({path:'/tmp/ustam-works-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(150);await page.screenshot({path:'/tmp/ustam-works-mobile.png',fullPage:false,animations:'disabled'});
 fail=true;await page.getByRole('button',{name:'Bu değişiklikleri projeye uygula'}).click();await page.waitForFunction(()=>document.querySelector('#view [role="status"]').textContent.includes('Work version changed'));assert.match(await page.locator('#view [role="status"]').innerText(),/Güncel kayıtları/);await page.getByRole('button',{name:'Bu değişiklikleri projeye uygula'}).click();await page.waitForFunction(()=>document.querySelector('[data-work-id="one"]').textContent.includes('Uygulandı'));assert.equal(posts.at(-1).version,2);assert.equal(posts.at(-1).integration_hash,hash('combined'));assert.equal(posts.at(-1).approve,true);assert.notEqual(posts.at(-1).operation_id,posts.at(-2).operation_id);
 await page.locator('[data-work-id="two"]').getByRole('button',{name:'Kaydı iptal et'}).click();await page.getByRole('button',{name:'Kaydı sürdür'}).waitFor();await page.getByRole('button',{name:'Kaydı sürdür'}).click();await page.waitForFunction(()=>document.querySelector('[data-work-id="two"]').textContent.includes('Kapsam paylaşıldı'));await page.getByRole('combobox',{name:'Dil / Language',exact:true}).selectOption('en');await page.getByRole('heading',{name:'Works',exact:true}).waitFor();assert.equal(await page.locator('#view textarea').count(),0);assert.equal(await page.getByRole('button',{name:'Approve this scope'}).count(),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,cases:['empty native flow','deduplicated decisions/options','stable cards','pending/idempotent action','helper report not proof','stale evidence blocks apply','bound apply/version refresh','mobile no overflow','decision draft survives refresh','cancel/resume record only','English/standing policy no approval duplicate','null/empty/missing SHA256 bindings fail closed','explicit approval flag required'],screenshots:['/tmp/ustam-works-desktop.png','/tmp/ustam-works-mobile.png']}));
 }finally{if(browser)await browser.close();worker.kill('SIGINT');}
})().catch(error=>{console.error(error);process.exitCode=1;});
