// Disposable usage UI checks: no live state, provider jobs, or project file writes.
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const path=require('node:path');
const fs=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{
 const worker=spawn(process.env.USTAM_TEST_PYTHON||'python3',['-u','tests/ustam_install_fixture.py'],{cwd:path.resolve(__dirname,'..')});let browser;
 try {
  const fixture=await new Promise((resolve,reject)=>{let output='';worker.stdout.on('data',chunk=>{output+=chunk;if(output.includes('\n'))resolve(JSON.parse(output.split('\n')[0]));});worker.stderr.on('data',chunk=>process.stderr.write(chunk));worker.on('exit',code=>reject(Error('Fixture exited '+code)));});
  browser=await chromium.launch({headless:true,channel:process.env.USTAM_TEST_BROWSER||'chrome'});const page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});const errors=[],posts=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()==='POST')posts.push(new URL(request.url()).pathname);});
  await page.addInitScript(()=>{const timer=window.setTimeout.bind(window);window.setTimeout=(fn,delay,...args)=>timer(fn,delay===180000?500:delay,...args);localStorage.setItem('ustam-language','en');localStorage.setItem('ustam-onboarded','1');});
  await page.goto(fixture.origin);await page.locator('#view > .cards').waitFor();
  // A distinct second-project team makes scope mixing observable.
  await page.evaluate(async ids=>{
   const read=async()=>await (await fetch('/api/bootstrap')).json();
   const send=async(path,body)=>{const state=await read();return await (await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Ustam-CSRF':state.csrf},body:JSON.stringify({...body,revision:state.revision})})).json();};
   const initial=await read();const team=JSON.parse(JSON.stringify(initial.orchestras.find(o=>o.provider==='codex')));team.id='beta-team';team.name='Beta configured team';team.helpers.forEach((h,index)=>{h.id='beta-'+index;h.name='Beta configured '+index;});
   await send('/api/orchestras',{action:'save',orchestra:team});await send('/api/defaults',{project_id:ids[1],override:{orchestras:{codex:team.id}}});
  },fixture.ids);
  await page.reload();await page.locator('#view > .cards').waitFor();
  const usage=async()=>{await page.locator('#nav').getByRole('button',{name:'Usage',exact:true}).click();await page.locator('.usage-grid').waitFor();await page.locator('.usage-session-details').evaluate(el=>el.open=true);await page.waitForTimeout(20);};
  const values=()=>page.locator('.metrics .metric strong').allTextContents();
  const unknown=async()=>{assert.deepEqual(await values(),['0','0','0','0']);assert.equal(await page.locator('.metric[data-usage-observed="false"]').count(),4);};
  const centered=async()=>assert.ok(await page.evaluate(()=>{const s=document.querySelector('.usage-grid .stage').getBoundingClientRect();const c=document.querySelector('.usage-grid .chief-actor').getBoundingClientRect();return Math.abs(s.x+s.width/2-c.x-c.width/2)<1;}));
  const stage=()=>page.locator('.usage-grid .stage');
  const motion=async()=>{
   const svg=stage().locator('.chief-actor svg');assert.equal(await svg.locator('use').getAttribute('href'),'#conductor-active');
   const sample=()=>page.evaluate(()=>{const arm=document.querySelector('#baton-arm-active');const note=document.querySelector('#conductor-active text');return {arm:arm.transform.animVal.getItem(0).matrix.a,note:note.transform.animVal.getItem(0).matrix.f,opacity:getComputedStyle(note).opacity};});
   const first=await sample();const frame=await svg.screenshot();await page.waitForTimeout(650);const next=await sample();const after=await svg.screenshot();assert.notEqual(first.arm,next.arm);assert.notEqual(first.note,next.note);assert.notEqual(first.opacity,next.opacity);assert.equal(frame.equals(after),false);
   return {first,next};
  };
  const actorSelect=()=>({inputValue:async()=>await page.locator('.usage-session-item[aria-pressed="true"]').count()?await page.locator('.usage-session-item[aria-pressed="true"]').getAttribute('data-session-index'):'',selectOption:async index=>await page.locator('.usage-session-item[data-session-index="'+index+'"]').click()});
  let report={status:'unavailable',source:'none',totals:{total_tokens:0,input_tokens:0,output_tokens:0,cached_input_tokens:0}};
  let release=null,scripted=null,usageRequests=0;
  const fixtureReport=input=>{
   const value=JSON.parse(JSON.stringify(input));value.installation_boundary??={status:'verified',started_at:'2000-01-01T00:00:00Z'};
   const stamp=new Date().toISOString();
   if(!value.records&&(value.actors||value.runs)){
    value.records=[];const append=(a,run_id=null)=>{const models=a.model?[a.model]:(a.models||[]).map(m=>m.id||m);const efforts=a.effort?[a.effort]:(a.efforts||[]).map(e=>e.id||e);for(let index=0;index<Math.max(1,models.length,efforts.length);index++){const usage={};if(!index)for(const key of ['total_tokens','input_tokens','output_tokens','cached_input_tokens'])if(typeof a[key]==='number')usage[key]=a[key];value.records.push({actor_id:a.id,run_id,timestamp:stamp,usage,model:models[index],effort:efforts[index]});}};
    (value.actors||[]).forEach(a=>append(a));(value.runs||[]).forEach(r=>(r.actors||[]).forEach(a=>append(a,r.id)));
   }
   for(const record of value.records||[])record.timestamp??=stamp;
   return value;
  };
  await page.route('**/api/usage?**',async route=>{usageRequests++;const step=scripted?.shift();if(step?.wait)await step.wait;if(release)await release;await route.fulfill(step?.error?{status:408,json:{ok:false,error:step.error}}:{json:{ok:true,result:fixtureReport(report)}});});
  const load=async()=>{await page.getByRole('button',{name:/^(Load usage|Kullanımı getir)$/}).click();await page.waitForFunction(()=>!document.querySelector('#notice').classList.contains('busy'));};
  await usage();assert.equal(await page.getByRole('heading',{name:'Usage details',exact:true}).count(),1);assert.ok(await stage().locator('.stage-helper .actor-model-value').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize)>=14));assert.ok(await stage().locator('.stage-helper .actor-metadata-label').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize)>=12));assert.equal(await stage().locator('.stage-helper').count(),4);assert.equal(await page.locator('.usage-team-name').innerText(),'codex team');assert.deepEqual(await page.locator('.usage-team-chips .badge').allTextContents(),['Codex','4 helpers']);assert.match(await page.locator('.usage-team-note').innerText(),/No usage data yet/);await centered();assert.equal(await stage().locator('.chief-actor .actor-model-value').innerText(),'GPT 6.1 sol');assert.equal(await stage().locator('.chief-actor .actor-effort-value').innerText(),'Medium');assert.equal(await stage().locator('.stage-helper .actor-metadata').count(),4);const reducedMotion=await motion();await page.emulateMedia({reducedMotion:'no-preference'});const standardMotion=await motion();await page.emulateMedia({reducedMotion:'reduce'});await page.screenshot({path:'/tmp/ustam-usage-readable-desktop.png',fullPage:true});await unknown();
  await load();await unknown();assert.equal(await stage().locator('.stage-helper').count(),4);assert.equal(await stage().locator('small:visible').filter({hasText:/^0$/}).count(),5);await page.evaluate(()=>{window.usageHelper=document.querySelector('.stage-helper');window.usageChief=document.querySelector('.usage-grid .chief-actor');});await load();assert.ok(await page.evaluate(()=>window.usageHelper===document.querySelector('.stage-helper')&&window.usageChief===document.querySelector('.usage-grid .chief-actor')));
  await stage().getByRole('button',{name:'Implementation · 1 · 0 · No usage data yet',exact:true}).click();await unknown();assert.equal(await actorSelect().inputValue(),'2');
  // Actual actors are independent from configured slots. Repeated roles remain separate identities.
  const helpers=Array.from({length:11},(_,index)=>({id:'real-'+index,name:'Recorded worker '+index,role:'implementer',total_tokens:10+index,input_tokens:7+index,output_tokens:3,cached_input_tokens:1}));
  report={source:'fixture usage',totals:{total_tokens:1000,input_tokens:700,output_tokens:300,cached_input_tokens:120},actors:[{id:'root-a',name:'Recorded chief A',role:'chief',total_tokens:250,input_tokens:200,output_tokens:50,cached_input_tokens:20},...helpers,{id:'root-b',name:'Recorded chief B',role:'owner',total_tokens:400,input_tokens:300,output_tokens:100}],runs:[
   {id:'r1',name:'First run',totals:{total_tokens:42,input_tokens:31,output_tokens:11},actors:[{id:'one',name:'Same role A',role:'implementer',total_tokens:42,input_tokens:31,output_tokens:11}]},
   {id:'r2',name:'Second run',totals:{total_tokens:110,input_tokens:80,output_tokens:30},actors:[{id:'two',name:'Same role B',role:'implementer',total_tokens:60,input_tokens:40,output_tokens:20},{id:'three',name:'Same role C',role:'implementer',total_tokens:50,input_tokens:40,output_tokens:10}]},
   {id:'empty',name:'Run without actors',totals:{},actors:[]}
  ]};
  report.actors[0].model='recorded-chief-model';report.actors[0].effort='high';report.actors[1].models=[{id:'recorded-helper-model'}];report.actors[1].efforts=[{id:'low'}];report.actors[2].models=[{id:'recorded-first'},{id:'recorded-second'}];report.actors[2].efforts=[{id:'low'},{id:'high'}];
  await load();assert.equal(await stage().locator('.chief-actor .actor-model-value').innerText(),'recorded chief model');assert.equal(await stage().locator('.chief-actor .actor-effort-value').innerText(),'High');assert.equal(await stage().locator('[data-actor-id="real-0"] .actor-model-value').innerText(),'recorded helper model');assert.match(await stage().locator('[data-actor-id="real-1"] .actor-model-value').innerText(),/Multiple: recorded first · recorded second/);assert.equal(await stage().locator('[data-actor-id="real-2"] .actor-model-value').innerText(),'Unknown');assert.equal(await stage().locator('[data-actor-id="real-2"] .actor-effort-value').innerText(),'Unknown');
  // A stalled usage read must release its local loader and retain prior observations.
  const retained=await values();let finishStall;release=new Promise(resolve=>{finishStall=resolve;});
  await page.getByRole('button',{name:'Load usage',exact:true}).click();
  assert.equal(await page.getByLabel('Project',{exact:true}).isDisabled(),false);
  await page.getByRole('button',{name:'Load usage',exact:true}).waitFor();
  assert.deepEqual(await values(),retained);assert.match(await page.locator('#notice').innerText(),/timed out/);
  assert.equal(await page.getByRole('button',{name:'Load usage',exact:true}).isEnabled(),true);finishStall();release=null;
  let finishCancel;release=new Promise(resolve=>{finishCancel=resolve;});
  await page.getByRole('button',{name:'Load usage',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Load usage',exact:true}).waitFor();assert.deepEqual(await values(),retained);assert.match(await page.locator('#notice').innerText(),/cancelled/);finishCancel();release=null;
  const indexTimeout={code:'usage_index_timeout',message:'History index deadline'};
  let before=usageRequests;scripted=[{error:indexTimeout},{}];await load();assert.equal(usageRequests-before,2);assert.equal(scripted.length,0);assert.deepEqual(await values(),retained);
  before=usageRequests;scripted=[...Array.from({length:5},()=>({error:indexTimeout})),{}];await load();assert.equal(usageRequests-before,6);assert.equal(scripted.length,0);assert.deepEqual(await values(),retained);
  before=usageRequests;scripted=[...Array.from({length:6},()=>({error:indexTimeout})),{}];await load();assert.equal(usageRequests-before,6);assert.equal(scripted.length,1);assert.deepEqual(await values(),retained);
  before=usageRequests;scripted=[{error:{code:'invalid_request',message:'Adapter lock timeout'}},{}];await load();assert.equal(usageRequests-before,1);assert.equal(scripted.length,1);
  // Cancellation during a continuation prevents any further request.
  let finishContinuation;const continuationWait=new Promise(resolve=>{finishContinuation=resolve;});
  before=usageRequests;scripted=[{error:indexTimeout},{wait:continuationWait},{}];
  await page.getByRole('button',{name:'Load usage',exact:true}).click();await page.getByRole('button',{name:'Scanning usage…',exact:true}).waitFor();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Load usage',exact:true}).waitFor();assert.equal(usageRequests-before,2);assert.deepEqual(await values(),retained);finishContinuation();scripted=null;
  // A project switch aborts a pending continuation and preserves the new scope.
  let finishContext;const contextWait=new Promise(resolve=>{finishContext=resolve;});
  before=usageRequests;scripted=[{error:indexTimeout},{wait:contextWait},{}];
  await page.getByRole('button',{name:'Load usage',exact:true}).click();await page.getByRole('button',{name:'Scanning usage…',exact:true}).waitFor();
  await page.getByLabel('Project',{exact:true}).selectOption(fixture.ids[1]);await page.getByRole('button',{name:'Load usage',exact:true}).waitFor();await unknown();assert.equal(usageRequests-before,2);finishContext();scripted=null;
  await page.getByLabel('Project',{exact:true}).selectOption(fixture.ids[0]);
  await load();
  assert.equal(await stage().locator('.team-character:visible').count(),13);assert.equal(await stage().locator('[data-actor-id="real-10"]').count(),1);assert.deepEqual(await page.locator('.usage-team-chips .badge').allTextContents(),['Codex','13 recorded sessions']);await centered();assert.equal(await stage().getByText('explorer',{exact:true}).count(),0);assert.deepEqual(await values(),['967','743','224','31']);
  await page.evaluate(()=>{window.usageHelper=document.querySelector('.stage-helper');});await page.getByLabel('Metric to display',{exact:true}).selectOption('cached');assert.ok(await page.evaluate(()=>window.usageHelper===document.querySelector('.stage-helper')));assert.equal(await stage().locator('[data-actor-id="root-b"] small').innerText(),'0');assert.equal(await stage().locator('[data-actor-id="root-b"]').getAttribute('data-usage-observed'),'false');assert.match(await page.locator('.usage-team-note').innerText(),/Some usage data is not available yet/);await page.getByLabel('Metric to display',{exact:true}).selectOption('total');
  await stage().locator('[data-actor-id="real-10"]').click();assert.deepEqual(await values(),['20','17','3','1']);await actorSelect().selectOption('0');assert.deepEqual(await values(),['250','200','50','20']);
  await page.getByLabel('Run',{exact:true}).selectOption('r1');assert.equal(await actorSelect().inputValue(),'');assert.equal(await stage().locator('.team-character:visible').count(),1);assert.equal(await stage().locator('.chief-actor:visible').count(),0);assert.deepEqual(await values(),['42','31','11','0']);
  await page.getByLabel('Run',{exact:true}).selectOption('r2');assert.equal(await stage().locator('.team-character:visible').count(),2);await stage().locator('[data-actor-id="three"]').click();assert.deepEqual(await values(),['50','40','10','0']);
  await page.getByLabel('Run',{exact:true}).selectOption('empty');await unknown();assert.equal(await stage().locator('.stage-helper').count(),4);assert.match(await page.locator('.usage-team-source').innerText(),/No usage data yet/);
  report={source:'scoped fixture',records:[{thread:'scope-root',session_id:'scope-root',model:'scope-only-model',effort:'high',usage:{total_tokens:25}}],orchestra:{scopes:[{id:'scope-root',name:'Scoped run'}],actors:[{id:'scope-root',role:'chief',models:[{id:'other-run-model'}],efforts:[{id:'low'}]}]}};await load();await page.getByLabel('Run',{exact:true}).selectOption('scope-root');assert.equal(await stage().locator('.actor-model-value').innerText(),'scope only model');assert.equal(await stage().locator('.actor-effort-value').innerText(),'High');
  await page.getByLabel('Tool',{exact:true}).selectOption('claude');await unknown();assert.equal(await page.getByLabel('Run',{exact:true}).locator('option').count(),1);assert.match(await page.locator('.usage-team-source').innerText(),/claude team/);assert.equal(await actorSelect().inputValue(),'');
  await page.getByLabel('Project',{exact:true}).selectOption(fixture.ids[1]);await page.getByLabel('Tool',{exact:true}).selectOption('codex');await unknown();assert.match(await page.locator('.usage-team-source').innerText(),/Beta configured team/);assert.equal(await stage().getByText('Beta configured 3',{exact:true}).count(),0);assert.equal(await page.locator('.usage-session-item').count(),5);
  // Navigation must retain selection but cannot reuse records from another project/provider.
  await page.locator('#nav').getByRole('button',{name:'My projects',exact:true}).click();await usage();assert.equal(await page.getByLabel('Project',{exact:true}).inputValue(),fixture.ids[1]);assert.equal(await page.getByLabel('Tool',{exact:true}).inputValue(),'codex');await unknown();
  // Late responses from a detached usage view cannot replace the new view's cache.
  let complete;release=new Promise(resolve=>{complete=resolve;});
  await page.getByRole('button',{name:'Load usage',exact:true}).click();await page.locator('#nav').getByRole('button',{name:'My projects',exact:true}).click();complete();release=null;await page.waitForFunction(()=>!document.querySelector('#notice').classList.contains('busy'));await usage();await unknown();assert.match(await page.locator('.usage-team-source').innerText(),/Beta configured team/);
  // Periods use cached request deltas and every summary follows the selected metric/run.
  const stamps=await page.evaluate(()=>{const d=new Date();d.setHours(0,0,0,0);const local=x=>[x.getFullYear(),String(x.getMonth()+1).padStart(2,'0'),String(x.getDate()).padStart(2,'0')].join('-');const older=new Date(d);older.setDate(older.getDate()-10);return {today:d.toISOString(),older:older.toISOString(),day:local(d)};});
  report={platform:'codex',status:'available',source:'dated request fixture',records:[
   {thread:'date-chief',timestamp:stamps.today,usage:{total_tokens:10,input_tokens:8,output_tokens:2,cached_input_tokens:6}},
   {thread:'date-helper',timestamp:stamps.today,usage:{total_tokens:20,input_tokens:14,output_tokens:6,cached_input_tokens:5}},
   {thread:'date-helper',timestamp:stamps.today,usage:{total_tokens:5,input_tokens:4,output_tokens:1,cached_input_tokens:2}},
   {thread:'other-chief',timestamp:stamps.older,usage:{total_tokens:40,input_tokens:30,output_tokens:10,cached_input_tokens:20}},
   {thread:'unclassified',timestamp:stamps.today,usage:{total_tokens:3,input_tokens:2,output_tokens:1}},
   {thread:'date-helper',timestamp:'unknown',usage:{total_tokens:7,input_tokens:5,output_tokens:2,cached_input_tokens:1}}
  ],agents:[{id:'date-chief',source:'root'},{id:'date-helper',source:'subagent',parent:'date-chief'},{id:'other-chief',source:'root'}],orchestra:{scopes:[{id:'date-chief',name:'Recent work'},{id:'other-chief',name:'Older work'}],actors:[{id:'date-chief',kind:'conductor',role:'chief'},{id:'date-helper',kind:'helper',role:'implementer'},{id:'other-chief',kind:'conductor',role:'chief'},{id:'unclassified',name:'Chief by name only',role:'unrecognized'}]}};
  await load();const allRequests=usageRequests;const summary=id=>page.locator('.usage-group[data-group="'+id+'"]');assert.equal(await summary('all').locator('strong').innerText(),'78');assert.equal(await summary('helpers').locator('strong').innerText(),'25');assert.match(await summary('helpers').innerText(),/1 recorded sessions/);
  const retainedActor=await page.locator('[data-actor-id="date-helper"]').elementHandle();
  await page.getByLabel('Period',{exact:true}).selectOption('7');assert.equal(usageRequests,allRequests);assert.equal(await summary('all').locator('strong').innerText(),'38');assert.equal(await summary('chiefs').locator('strong').innerText(),'10');assert.equal(await summary('helpers').locator('strong').innerText(),'25');assert.equal(await summary('unknown').locator('strong').innerText(),'3');assert.match(await page.locator('.usage-date-coverage').innerText(),/1 records with unknown dates/);assert.ok(await retainedActor.evaluate(el=>el===document.querySelector('[data-actor-id="date-helper"]')));
  await summary('helpers').click();assert.deepEqual(await values(),['25','18','7','7']);await page.getByLabel('Metric to display',{exact:true}).selectOption('cached');assert.equal(await summary('helpers').locator('strong').innerText(),'7');assert.equal(await summary('chiefs').locator('strong').innerText(),'6');assert.equal(usageRequests,allRequests);
  await page.getByLabel('Run',{exact:true}).selectOption('date-chief');assert.equal(await summary('all').locator('strong').innerText(),'13');assert.equal(await summary('unknown').locator('strong').innerText(),'0');await page.getByLabel('Metric to display',{exact:true}).selectOption('total');assert.equal(await summary('all').locator('strong').innerText(),'35');
  await page.getByLabel('Run',{exact:true}).selectOption('');await page.getByLabel('Period',{exact:true}).selectOption('30');assert.equal(await summary('all').locator('strong').innerText(),'78');assert.equal(usageRequests,allRequests);
  await page.getByLabel('Period',{exact:true}).selectOption('custom');assert.equal(await page.getByRole('button',{name:'Load usage',exact:true}).isDisabled(),true);await page.getByLabel('Start date',{exact:true}).fill(stamps.day);await page.getByLabel('End date',{exact:true}).fill(stamps.day);await page.getByLabel('End date',{exact:true}).press('Tab');assert.equal(await summary('all').locator('strong').innerText(),'38');assert.equal(usageRequests,allRequests);
  await page.getByLabel('Start date',{exact:true}).fill('2099-12-31');await page.getByLabel('Start date',{exact:true}).press('Tab');assert.equal(await page.getByRole('button',{name:'Load usage',exact:true}).isDisabled(),true);assert.match(await page.locator('.usage-dates .error-text').innerText(),/start cannot follow/);assert.equal(usageRequests,allRequests);
  await page.getByLabel('Period',{exact:true}).selectOption('all');assert.equal(await summary('all').locator('strong').innerText(),'78');assert.equal(usageRequests,allRequests);
  // Parent-linked sanitized OpenCode session records retain component semantics.
  await page.getByLabel('Tool',{exact:true}).selectOption('opencode');report={platform:'opencode',status:'available',source:'sanitized export fixture',records:[{thread:'oc-root',created:Date.parse(stamps.today),observed:{input:5,output:2,reasoning:1,cache_read:3,cache_write:4}},{thread:'oc-child',created:Date.parse(stamps.today),observed:{input:2,output:1,cache_read:7}}],orchestra:{roots:[{id:'oc-root',nodes:[{id:'oc-root',parent:null,models:{}},{id:'oc-child',parent:'oc-root',models:{}}]}]}};await load();await page.getByLabel('Period',{exact:true}).selectOption('7');assert.equal(await summary('all').locator('strong').innerText(),'25');assert.equal(await summary('helpers').locator('strong').innerText(),'10');await page.getByLabel('Metric to display',{exact:true}).selectOption('cached');assert.equal(await summary('all').locator('strong').innerText(),'10');
  await page.getByLabel('Tool',{exact:true}).selectOption('claude');report={platform:'claude',status:'unavailable',source:'none'};await load();await unknown();assert.equal(await summary('chiefs').getAttribute('data-usage-observed'),'false');
  await page.getByLabel('Period',{exact:true}).selectOption('all');await page.getByLabel('Metric to display',{exact:true}).selectOption('total');report={source:'scoped fixture',records:[{thread:'scope-root',session_id:'scope-root',model:'scope-only-model',effort:'high',usage:{total_tokens:25}}],orchestra:{scopes:[{id:'scope-root',name:'Scoped run'}],actors:[{id:'scope-root',role:'chief'}]}};
  // Layout with all recorded identities remains within the viewport; Turkish fallback remains explicit.
  await load();await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByLabel('Tool',{exact:true}).selectOption('opencode');await page.locator('#language').selectOption('tr');await page.locator('.usage-session-details').evaluate(el=>el.open=true);await page.waitForTimeout(20);assert.equal(await page.locator('.usage-team-name').innerText(),'opencode team');assert.deepEqual(await page.locator('.usage-team-chips .badge').allTextContents(),['OpenCode','4 yardımcı']);assert.match(await page.locator('.usage-team-note').innerText(),/Henüz kullanım verisi yok/);assert.deepEqual(await values(),['0','0','0','0']);await centered();assert.equal(await stage().locator('.chief-actor .actor-effort-value').innerText(),'Yok');assert.equal(await stage().locator('.actor-metadata-label').filter({hasText:/^Düşünme düzeyi$/}).count(),5);await motion();await page.screenshot({path:'/tmp/ustam-usage-readable-390.png',fullPage:true});assert.equal(await stage().locator('.stage-helper').count(),4);assert.equal(await page.getByRole('heading',{name:'Kullanım detayları',exact:true}).count(),1);assert.equal(await page.getByLabel('Görev grubu seç',{exact:true}).count(),1);assert.ok(await stage().locator('.stage-helper .actor-model-value').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize)>=14));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  // A tall stage cannot stretch the detail rows or actor control.
  const layoutEvidence=[];
  const compactDetails=async(name,desktop)=>{
   const dimensions=await page.evaluate(()=>{
    const rect=selector=>document.querySelector(selector).getBoundingClientRect();
    const panel=rect('.usage-selection-panel'),heading=rect('.usage-selection-panel h2'),label=rect('.usage-selection-panel .field>span'),select=rect('.usage-selection-panel select');
    return {selectHeight:select.height,headingGap:label.top-heading.bottom,labelGap:select.top-label.bottom,headingCenter:Math.abs(heading.x+heading.width/2-panel.x-panel.width/2),detailHeight:rect('.usage-details').height,stageHeight:rect('.usage-grid .stage').height,cardHeights:[...document.querySelectorAll('.metric')].map(el=>el.getBoundingClientRect().height),overflow:document.documentElement.scrollWidth>innerWidth};
   });
   assert.ok(dimensions.selectHeight>=44&&dimensions.selectHeight<=52);assert.ok(dimensions.headingGap>=16&&dimensions.headingGap<=24);assert.ok(dimensions.labelGap>=6&&dimensions.labelGap<=8);assert.ok(dimensions.headingCenter<1);assert.ok(dimensions.cardHeights.every(height=>height<190));assert.equal(dimensions.overflow,false);
   layoutEvidence.push({name,...dimensions});await page.screenshot({path:'/tmp/ustam-usage-layout-'+name+'.png',fullPage:true});
  };
  await page.locator('#language').selectOption('en');await page.getByLabel('Tool',{exact:true}).selectOption('codex');await page.setViewportSize({width:1280,height:900});
  for(const count of [5,11]){
   report={source:'isolated layout fixture',totals:{total_tokens:120,input_tokens:90,output_tokens:30,cached_input_tokens:10},actors:[{id:'layout-chief',role:'chief',name:'Layout chief',model:'recorded-chief-model',effort:'high'},...Array.from({length:count},(_,index)=>({id:'layout-'+index,role:'implementer',name:'Layout helper '+index,model:'recorded-helper-model',effort:'medium'}))]};
   await load();assert.equal(await stage().locator('.stage-helper').count(),count);await compactDetails(count+'-desktop',true);
  }
  await page.setViewportSize({width:390,height:844});await compactDetails('11-mobile-en',false);await page.locator('#language').selectOption('tr');await compactDetails('11-mobile-tr',false);
  // Default summaries are compact; all individual identities remain searchable.
  const roleInventory=[{id:'roles-chief',kind:'conductor',name:'Helper'},...Array.from({length:46},(_,index)=>({id:'roles-'+String(index).padStart(2,'0'),kind:'helper',name:'Forge',role:index<20?'implementer':index<30?'explorer':'unrecognized',model:'real-model',effort:'medium'}))];
  report={status:'available',source:'isolated role fixture',actors:roleInventory,records:roleInventory.map(a=>({actor_id:a.id,timestamp:stamps.today,usage:{total_tokens:a.kind==='conductor'?5:1,input_tokens:1,output_tokens:0,cached_input_tokens:1}}))};
  await load();await page.locator('.usage-session-details').evaluate(el=>el.open=false);await page.waitForTimeout(30);
  assert.equal(await stage().locator('.team-character:visible').count(),4);assert.equal(await stage().locator('[data-role-key="chiefs"] strong').innerText(),'Şef');assert.equal(await page.getByLabel('Görev grubu seç',{exact:true}).locator('option').count(),7);assert.equal(await page.locator('.usage-session-item').count(),47);assert.equal(await stage().getByText('Forge',{exact:true}).count(),0);
  const beforeGroups=usageRequests;const retainedRole=await stage().locator('[data-role-key="implementer"]').elementHandle();await stage().locator('[data-role-key="implementer"]').click();assert.deepEqual(await values(),['20','20','0','20']);await page.getByLabel('Gösterilecek ölçü',{exact:true}).selectOption('cached');assert.ok(await retainedRole.evaluate(el=>el===document.querySelector('[data-role-key="implementer"]')));assert.equal(usageRequests,beforeGroups);
  await page.locator('.usage-session-details summary').first().click();await stage().locator('.stage-helper').first().waitFor({state:'visible'});assert.equal(await stage().locator('.stage-helper:visible').count(),46);assert.equal(await stage().locator('.chief-actor strong').innerText(),'Şef');const labels=await page.locator('.usage-session-item').allTextContents();assert.equal(new Set(labels).size,47);assert.ok(labels.includes('Yardımcı oturumu 1'));await page.getByLabel('Oturumlarda ara',{exact:true}).fill('Yardımcı oturumu 1');assert.equal(await page.locator('.usage-session-item').count(),8);await page.getByLabel('Oturumlarda ara',{exact:true}).fill('');assert.equal(await page.locator('.usage-session-item').count(),47);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('.usage-session-details summary').first().click();await stage().locator('.usage-role-stage').waitFor({state:'visible'});await page.getByLabel('Dönem',{exact:true}).selectOption('7');assert.equal(usageRequests,beforeGroups);assert.equal(await page.locator('.usage-group[data-group="all"] strong').innerText(),'47');await page.getByLabel('Gösterilecek ölçü',{exact:true}).selectOption('total');assert.equal(await page.locator('.usage-group[data-group="all"] strong').innerText(),'51');await page.screenshot({path:'/tmp/ustam-usage-roles-mobile-tr.png',fullPage:true});
  // Individual chief labels are distinct and use the full report identity order.
  report={status:'available',actors:[{id:'root-b',kind:'conductor',name:'Forge'},{id:'root-a',kind:'conductor',name:'Forge'}],records:[{actor_id:'root-a',timestamp:stamps.older,usage:{total_tokens:5}},{actor_id:'root-b',timestamp:stamps.today,usage:{total_tokens:11}}]};
  await page.getByLabel('Dönem',{exact:true}).selectOption('all');await load();await page.locator('.usage-session-details summary').first().click();await stage().locator('.chief-actor').waitFor({state:'visible'});
  const chiefSessionLabels=()=>page.locator('.usage-session-item').allTextContents();assert.deepEqual(await chiefSessionLabels(),['Şef oturumu 2','Şef oturumu 1']);await page.locator('.usage-session-item[data-session-id="root-a"]').click();assert.equal((await values())[0],'5');await load();assert.deepEqual(await chiefSessionLabels(),['Şef oturumu 2','Şef oturumu 1']);await page.getByLabel('Dönem',{exact:true}).selectOption('7');assert.deepEqual(await chiefSessionLabels(),['Şef oturumu 2']);await page.getByLabel('Oturumlarda ara',{exact:true}).fill('Şef oturumu 2');assert.equal(await page.locator('.usage-session-item').count(),1);await page.locator('.usage-session-item').click();assert.equal((await values())[0],'11');await page.getByLabel('Oturumlarda ara',{exact:true}).fill('');await page.getByLabel('Dönem',{exact:true}).selectOption('all');assert.deepEqual(await chiefSessionLabels(),['Şef oturumu 2','Şef oturumu 1']);assert.equal(await stage().locator('.chief-actor strong').innerText(),'Şef');
  report={status:'available',installation_boundary:{status:'verified',started_at:stamps.today,observed_at:new Date().toISOString(),conservative:true},actors:[{id:'old-session',kind:'helper'},{id:'new-session',kind:'helper'}],records:[{actor_id:'old-session',timestamp:stamps.older,usage:{total_tokens:100}},{actor_id:'new-session',timestamp:stamps.today,usage:{total_tokens:11}},{actor_id:'new-session',timestamp:'unknown',usage:{total_tokens:999}},{actor_id:'new-session',timestamp:new Date(Date.now()+86400000).toISOString(),usage:{total_tokens:800}}]};
  await load();assert.equal(await page.locator('.usage-group[data-group="all"] strong').innerText(),'11');assert.equal(await page.locator('.usage-session-item').count(),1);assert.match(await page.locator('.usage-installation-start').innerText(),/Doğrulanan kullanım başlangıcı/);assert.match(await page.locator('.usage-date-coverage').innerText(),/1 kayıt/);assert.equal(await page.locator('.usage-session-details summary').first().innerText(),'Yardımcıların kullanımını incele');assert.match(await page.locator('.usage-session-details').innerText(),/Şefin ve yardımcıların ayrı ayrı ne kadar kullandığını görün/);const cutoffRequests=usageRequests;await page.getByLabel('Dönem',{exact:true}).selectOption('30');assert.equal(usageRequests,cutoffRequests);assert.equal(await page.locator('.usage-group[data-group="all"] strong').innerText(),'11');
  report.installation_boundary={status:'unverified'};await load();await unknown();assert.equal(await page.locator('.usage-group[data-group="all"]').getAttribute('data-usage-observed'),'false');assert.equal(await page.locator('.usage-installation-start').innerText(),'Kurulum başlangıcı doğrulanamadı.');
  assert.deepEqual(fs.readdirSync(path.join(fixture.root,'Alpha')),[]);assert.deepEqual(fs.readdirSync(path.join(fixture.root,'Beta')),[]);assert.equal(posts.some(url=>url.startsWith('/api/jobs')),false);assert.deepEqual(errors,[]);
  console.log(JSON.stringify({ok:true,layoutEvidence,reducedMotion,standardMotion,browser:browser.version(),cases:['cached localcalendar date filters and invalid-range no request','chief/helper/unclassified summaries follow metric/run','sessionidentity counts preserve duplicate requests','OpenCode date+parent+cache components','Claude unavailable remains unobserved','typed index timeout continues within six requests and180s','generic adapter timeout never retries','continuation cancel/project switch stops retries','usage timeout releases local loader and retains prior data','usage cancellation and successful retry','configured model/effort on every actor','recorded model/effort unknown/multiple/scoped','automatic baton+notes with reduced/default motion','configured helpers without records','missing numeric0 remains unobserved with note','centered chief desktop/mobile','stable animation nodes on refresh','13 real identities without role merging or cap','actor selection','run reset/no fabricated chief','project/provider scoped cache','detached response ignored','EN/TR mobile fallback','no project writes or paid jobs']}));
 }finally{if(browser)await browser.close();worker.kill('SIGINT');}
})().catch(error=>{console.error(error);process.exitCode=1;});
