// Disposable source server + explicitly synthetic Antigravity API records; no provider execution.
const {chromium}=require('playwright');const {spawn}=require('node:child_process');const path=require('node:path');const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{
 const worker=spawn(process.env.USTAM_TEST_PYTHON||'python3',['-u','tests/ustam_install_fixture.py'],{cwd:path.resolve(__dirname,'..')});let browser;
 try{
 const fixture=await new Promise((resolve,reject)=>{let out='';worker.stdout.on('data',chunk=>{out+=chunk;if(out.includes('\n'))resolve(JSON.parse(out.split('\n')[0]));});worker.stderr.on('data',chunk=>process.stderr.write(chunk));worker.on('exit',code=>reject(Error('Fixture exited '+code)));});
 const evidence=process.env.USTAM_UI_EVIDENCE||'/tmp/ustam-antigravity-ui';fs.mkdirSync(evidence,{recursive:true});
 const caps={jobs:false,usage:false,role_effort:false,restore:true,native_concurrency_limit:false},roles=['explorer','implementer','verifier','reviewer'];
 const profiles=['balanced','quality','economy','quota-saver','custom'];const recommendations=Object.fromEntries(profiles.map(profile=>{const model=profile==='quality'?'pro':['economy','quota-saver'].includes(profile)?'flash':'inherit';return [profile,{chief:{model,effort:''},role_models:Object.fromEntries(roles.map(role=>[role,model])),role_efforts:Object.fromEntries(roles.map(role=>[role,''])),concurrency:1}];}));
 const catalog={provider:'antigravity',models:[{id:'inherit',label:'Inherit tool model',efforts:[]},{id:'flash',label:'Flash',efforts:[]},{id:'pro',label:'Pro',efforts:[]}],chief_efforts:[],profiles,roles,profile_recommendations:recommendations,max_concurrency:1,capabilities:caps,support_matrix:{cli:{status:'supported',version:'1.2.16',reason:''},native_agents:{status:'local_help_verified'},usage:{status:'unsupported'},jobs:{status:'unsupported'},legacy_ide:{status:'unverified'}},source:'Synthetic API fixture; no model access verified'};
 const saved={id:'antigravity-team',name:'Antigravity saved team',provider:'antigravity',chief:{model:'inherit',effort:''},helpers:roles.map(role=>({id:role,role,name:role,model:'inherit',effort:''})),concurrency:1,profile:'balanced',task_type:'feature'};
 let catalogLoaded=false;let current,previewMode='success',applyMode='success';const posts=[],errors=[],allRequests=[];
 browser=await chromium.launch({headless:true,channel:process.env.USTAM_TEST_BROWSER||'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1100}});page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>allRequests.push(new URL(request.url()).pathname));await page.addInitScript(()=>{localStorage.setItem('ustam-language','en');localStorage.setItem('ustam-onboarded','1');});
 await page.route('**/api/bootstrap',async route=>{if(!current){const response=await route.fetch();current=await response.json();current.providers=['codex','claude','opencode','antigravity'];current.selected_providers=[...current.providers];current.orchestras.push(saved);current.defaults.orchestras.antigravity=saved.id;assert.equal(current.capabilities.providers.antigravity.jobs.enabled,false);assert.deepEqual(current.capabilities.providers.antigravity.jobs.supported_roles,[]);}await route.fulfill({json:current});});
 await page.route('**/api/models?*',async route=>{if(new URL(route.request().url()).searchParams.get('provider')==='antigravity'){if(!catalogLoaded){const response=await route.fetch();const actual=await response.json();Object.assign(catalog,actual.result);catalog.support_matrix={...catalog.support_matrix,cli:{status:'supported',version:'1.2.16',reason:'Synthetic supported CLI; no native execution'},native_agents:{status:'local_help_verified'}};catalogLoaded=true;}return route.fulfill({json:{ok:true,result:catalog}});}await route.continue();});
 for(const endpoint of ['projects','orchestras','defaults'])await page.route('**/api/'+endpoint,async route=>{const body=route.request().postDataJSON();posts.push({endpoint,...body});if(endpoint==='orchestras'&&body.action==='save'){const actual=await page.request.get(fixture.origin+'/api/bootstrap');const bootstrap=await actual.json();const accepted=await route.fetch({postData:JSON.stringify({...body,revision:bootstrap.revision})});assert.equal(accepted.status(),200,'Actual source Hub rejected save: '+await accepted.text());current.orchestras=current.orchestras.filter(o=>o.id!==body.orchestra.id);current.orchestras.push(body.orchestra);}if(endpoint==='defaults'){if(body.override)current.project_overrides[body.project_id]=body.override;if(body.selected_providers)current.selected_providers=body.selected_providers;}if(endpoint==='projects'&&body.action==='selection')current.selected_projects=body.ids;current.revision++;await route.fulfill({json:current});});
 await page.route('**/api/preview',async route=>{const body=route.request().postDataJSON();posts.push({endpoint:'preview',...body});const results=body.project_ids.map(project_id=>previewMode==='success'?{project_id,ok:true,preview_id:'fixture-'+project_id,preview:{ok:true,can_apply:true,phases:[{phase:'preview',status:'completed'}],changes:[{path:'.agents/agents/chief.md'}]}}:{project_id,ok:false,stage:'preflight',recovery_status:'not_started',error:{message:'Antigravity CLI is missing or unsupported; no project changes made'}});await route.fulfill({json:{ok:true,results}});});
 await page.route('**/api/apply',async route=>{const body=route.request().postDataJSON();posts.push({endpoint:'apply',...body});const results=body.preview_ids.map(preview_id=>applyMode.startsWith('recovery-')?{preview_id,project_id:preview_id.replace('fixture-',''),ok:false,stage:applyMode==='recovery-not_started'?'preflight':'verified',recovery_status:applyMode.slice(9),error:'Synthetic stage failure; no actual execution'}:({preview_id,project_id:preview_id.replace('fixture-',''),ok:true,result:{provider:'antigravity',ok:true,applied:true,verified:!['unverified','receipt-only'].includes(applyMode),backup_id:'fixture-backup',phases:(['unverified','flag-only'].includes(applyMode)?['preflight','backup','applied']:['preflight','backup','applied','verified']).map(phase=>({phase,status:'completed'})),changed_files:['.agents/agents/chief.md']}}));await route.fulfill({json:{ok:true,results}});});
 await page.goto(fixture.origin);await page.locator('.select-project').first().waitFor();await page.locator('#nav').getByRole('button',{name:'Settings',exact:true}).click();for(const provider of ['Codex','Claude Code','OpenCode','Antigravity'])assert.equal(await page.getByRole('checkbox',{name:provider,exact:true}).count(),1);assert.equal(posts.length,0);await page.screenshot({path:path.join(evidence,'four-tools-desktop.png')});
 await page.locator('#nav').getByRole('button',{name:'My projects',exact:true}).click();await page.locator('#view > .cards article').first().getByRole('button',{name:'Change team',exact:true}).click();for(const provider of ['codex','claude','opencode']){await page.locator('#project-orchestra-choice').getByLabel('Tool',{exact:true}).selectOption(provider);await page.locator('[data-profile="balanced"] button').waitFor();assert.equal(await page.locator('#project-orchestra-choice').getByLabel('Tool',{exact:true}).inputValue(),provider);assert.ok(await page.locator('[data-profile="balanced"] button').isEnabled());}await page.locator('#project-orchestra-choice').getByLabel('Tool',{exact:true}).selectOption('antigravity');await page.locator('[data-profile="balanced"] button').waitFor();await page.locator('[data-profile="balanced"]').getByRole('button',{name:'Review team',exact:true}).click();const preview=page.locator('#inline-team-preview');await preview.waitFor();for(let i=0;i<4;i++){await preview.locator('.stage-helper').first().click();await preview.getByRole('button',{name:'Remove',exact:true}).click();}assert.ok(await preview.getByRole('button',{name:'Use for this project',exact:true}).isDisabled());await preview.getByRole('button',{name:'Close',exact:true}).click();await page.locator('[data-profile="balanced"]').getByRole('button',{name:'Review team',exact:true}).click();await preview.waitFor();
 assert.equal(await preview.getByLabel('Review depth',{exact:true}).count(),0);assert.equal(await preview.getByLabel('Native project concurrency limit',{exact:true}).count(),0);assert.equal(await preview.locator('.actor-effort-value:visible').count(),0);assert.deepEqual(await preview.getByLabel('Model',{exact:true}).locator('option').evaluateAll(options=>options.map(o=>o.value).filter(Boolean)),['inherit','flash','pro']);
 await preview.locator('.chief-actor svg').evaluate(el=>window.antiChief=el);await preview.locator('.stage-helper').first().click();await preview.getByLabel('Model',{exact:true}).selectOption('flash');assert.ok(await preview.locator('.chief-actor svg').evaluate(el=>el===window.antiChief));await page.screenshot({path:path.join(evidence,'antigravity-ready-desktop.png')});
 await preview.getByRole('button',{name:'Use for this project',exact:true}).click();await page.locator('.project-flow').waitFor();const savedPayload=posts.find(p=>p.endpoint==='orchestras'&&p.orchestra.provider==='antigravity').orchestra;assert.equal(savedPayload.chief.effort,'');assert.equal(savedPayload.helpers[0].effort,'');assert.equal(savedPayload.helpers[0].model,'flash');assert.equal(savedPayload.concurrency,1);assert.equal(savedPayload.helpers.length,4);assert.deepEqual(savedPayload.helpers.map(h=>h.role),['explorer','implementer','verifier','reviewer']);assert.equal(posts.filter(p=>['preview','apply'].includes(p.endpoint)).length,0);
 const flow=()=>page.locator('.project-flow[data-provider="antigravity"]');await flow().getByRole('button',{name:'Install in project',exact:true}).click();await page.locator('#modal .result').waitFor();await page.waitForFunction(()=>!document.querySelector('#notice').classList.contains('busy'));assert.equal(posts.filter(p=>p.endpoint==='preview').length,1);assert.equal(posts.filter(p=>p.endpoint==='apply').length,1);
 assert.deepEqual(await page.locator('#modal .install-phases li').allTextContents(),['Check · Completed','Backup · Completed','Install · Completed','Verify · Completed']);assert.match(await page.locator('#modal').innerText(),/Antigravity in this project folder/);await page.screenshot({path:path.join(evidence,'antigravity-install-desktop.png')});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(evidence,'antigravity-install-mobile.png')});await page.locator('#modal .install-phases').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(evidence,'antigravity-install-receipts-mobile.png')});await page.setViewportSize({width:1440,height:1100});
 await page.locator('#modal .modal-actions').getByRole('button',{name:'Close',exact:true}).click();
 assert.equal(await page.getByText('Installation verified in this session',{exact:true}).count(),1);
 await flow().getByRole('button',{name:'Change team',exact:true}).click();await page.locator('#project-orchestra-choice').getByRole('button',{name:'Choose / create your own orchestra',exact:true}).click();await page.getByRole('button',{name:'Create another orchestra',exact:true}).click();const custom=page.locator('.inline-team-editor');await custom.getByLabel('Model',{exact:true}).first().waitFor();assert.equal(await custom.getByLabel('Review depth',{exact:true}).count(),0);assert.equal(await custom.getByRole('spinbutton').count(),0);assert.equal(await custom.locator('.actor-effort-value:visible').count(),0);await custom.getByLabel('Model',{exact:true}).first().selectOption('pro');await custom.getByRole('button',{name:'Use for this project',exact:true}).click();await flow().waitFor();const lastSaved=posts.filter(p=>p.endpoint==='orchestras').at(-1).orchestra;assert.equal(lastSaved.chief.model,'pro');assert.equal(lastSaved.chief.effort,'');assert.equal(lastSaved.concurrency,1);
 for(const mode of ['flag-only','receipt-only']){applyMode=mode;await flow().getByRole('button',{name:'Install in project',exact:true}).click();await page.locator('#modal .result.error').waitFor();await page.waitForFunction(()=>!document.querySelector('#notice').classList.contains('busy'));assert.equal(await page.getByText('Installation verified in this session',{exact:true}).count(),0);assert.match(await page.locator('#modal').innerText(),/verification is incomplete/);await page.locator('#modal .modal-actions').getByRole('button',{name:'Close',exact:true}).click();}applyMode='success';
 for(const status of ['missing','unsupported']){const beforePreview=posts.filter(p=>p.endpoint==='preview').length,beforeApply=posts.filter(p=>p.endpoint==='apply').length;catalog.support_matrix.cli={status,version:status==='missing'?null:'0.1.0',reason:'Synthetic preflight: native CLI unavailable'};catalog.support_matrix.native_agents.status='unsupported';await flow().getByRole('button',{name:'Install in project',exact:true}).click();await page.locator('#modal .result.error').waitFor();await page.waitForFunction(()=>!document.querySelector('#notice').classList.contains('busy'));assert.equal(posts.filter(p=>p.endpoint==='preview').length,beforePreview);assert.equal(posts.filter(p=>p.endpoint==='apply').length,beforeApply);assert.match(await page.locator('#modal').innerText(),status==='missing'?/command-line tool was not found/:/version does not support installation/);await page.locator('#modal .modal-actions').getByRole('button',{name:'Close',exact:true}).click();}
 catalog.support_matrix.cli={status:'supported',version:'1.2.16',reason:''};catalog.support_matrix.native_agents.status='local_help_verified';
 for(const [recovery,message] of [['not_started','Project files were not changed.'],['rolled_back','Changes made by this operation were rolled back.'],['conflicts_retained','Conflicting files were retained. Review the details.']]){applyMode='recovery-'+recovery;await flow().getByRole('button',{name:'Install in project',exact:true}).click();await page.locator('#modal .result.error').waitFor();await page.waitForFunction(()=>!document.querySelector('#notice').classList.contains('busy'));assert.match(await page.locator('#modal .install-failure').innerText(),/stage did not complete/);assert.ok((await page.locator('#modal').innerText()).includes(message));assert.equal(await page.locator('#modal [data-phase="verified"]').count(),0);await page.locator('#modal .modal-actions').getByRole('button',{name:'Close',exact:true}).click();}applyMode='success';
 // A stale stored effort and even malformed catalog effort options cannot leak into a save.
 const staleTeam=current.orchestras.find(o=>o.id===lastSaved.id);staleTeam.chief.effort='high';for(const model of catalog.models)model.efforts=['high'];await page.reload();await page.locator('.select-project').first().waitFor();await page.locator('#nav').getByRole('button',{name:'My orchestras',exact:true}).click();const staleCard=page.locator('#view > .cards article').filter({hasText:staleTeam.name}).last();await staleCard.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#modal').getByLabel('Model',{exact:true}).first().waitFor();const saveEdited=page.locator('#modal').getByRole('button',{name:'Save orchestra',exact:true});assert.ok(await saveEdited.isDisabled());assert.equal(await page.locator('#modal').getByLabel('Review depth',{exact:true}).count(),0);assert.equal(await page.locator('#modal .actor-effort-value:visible').count(),0);await page.locator('#modal').getByLabel('Model',{exact:true}).first().selectOption('flash');assert.ok(await saveEdited.isEnabled());await page.screenshot({path:path.join(evidence,'antigravity-custom-desktop.png')});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(evidence,'antigravity-custom-mobile.png')});await page.setViewportSize({width:1440,height:1100});await saveEdited.click();await page.waitForFunction(()=>!document.querySelector('#modal').open);assert.equal(current.orchestras.find(o=>o.id===lastSaved.id).chief.effort,'');for(const model of catalog.models)model.efforts=[];
 await page.locator('#nav').getByRole('button',{name:'Usage',exact:true}).click();await page.locator('#view').getByLabel('Tool',{exact:true}).selectOption('antigravity');assert.ok(await page.locator('.usage-unsupported').isVisible());assert.equal(await page.locator('.metric:visible,.usage-group:visible').count(),0);assert.ok(await page.getByRole('button',{name:'Load usage',exact:true}).isDisabled());assert.equal(allRequests.filter(p=>p==='/api/usage').length,0);assert.equal(await page.locator('.job-box,textarea').count(),0);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(evidence,'antigravity-usage-mobile.png')});await page.locator('#language').selectOption('tr');assert.match(await page.locator('.usage-unsupported').innerText(),/Ölçülmüş/);await page.locator('#nav').getByRole('button',{name:'Ayarlar',exact:true}).click();for(const provider of ['Codex','Claude Code','OpenCode','Antigravity'])assert.equal(await page.getByRole('checkbox',{name:provider,exact:true}).count(),1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(evidence,'four-tools-mobile-tr.png'),fullPage:true});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,synthetic:true,cases:['actual source catalog and Hub validate saves with disabled Jobs empty-role metadata','four selectable providers/ready profiles remain usable','only inherit/flash/pro','unsupported effort/concurrency hidden','actor DOM stable','ready save no install','one click preview/apply','usage unsupported without observed zeros or GET','custom model-only editor','stale high effort cannot be saved despite malformed catalog','verified marker AND receipt required','missing/old CLI blocks preview/apply','real receipts displayed as four stages','structured failures show only declared stage/recovery status','EN/TR mobile'],screenshots:evidence}));
 }finally{if(browser)await browser.close();worker.kill('SIGINT');}
})().catch(error=>{console.error(error);process.exitCode=1;});
